### PR TITLE
Remove /V4.0 in API endpoints

### PR DESCRIPTION
**Pull request by nguyenhongphat0**
Please remember to update `URL_PREFIX='api/'` in `config/settings/<hostname>.py` after rolling out these changes to other live instances!

### CODE REVIEW

**Review by gloriajw — COMMENTED** [review]
Phat, pls change this in nginx:
 location ^/(stage_graphql|user_graphql|config_graphql|studio_graphql|access_token) 
 to this:
 location / 
 and make this the last match in nginx.

**Comment by nguyenhongphat0** [comment]
Doing so will prevent access to stages (screenshot below :point_down:). If you access the foyer => click on stage, vue can handle it. But it you access the stage directly from the url (for example: https://dev-app1.upstage.org.nz/demo), it would pass the handler to flask and failed.
image

**Comment by gloriajw** [comment]
I see. Then please use /api in nginx, and put all graphql endpoints behind /api. I don't want you to have to change nginx every time you add a new graphql namespace. Note that nginx can be directed to strip off the /api portion if you want it to, before proxying the request to flask.

**Comment by helenvarley** [comment]
> t if you access the stage directly from the url (for example: https://dev-app1.upstage.org.nz/demo),

this is important - we need to put direct stage urls in publicity for shows, e.g. in emails, on websites, on social media as it's much easier for the audience.

**Comment by gloriajw** [comment]
@helenvarley I fully understand, and please realize that when we discuss nginx paths, they do not have to directly reflect the path on the back end. it is simply a mapping. No one is disabling your ability to use a link directly off the root. But we do need to use good conventions on routing between vuejs (which may process some paths off of root directly) and flask, and this is what we're discussing.

**Comment by helenvarley** [comment]
sorry if my technical incompetence was showing :wink:

**Comment by gloriajw** [comment]
It's ok, I want you to comment. I don't want to discourage comments from anyone. I also want to assure you that we will never limit what you want to do with the platform, and we'll never create conventions that contradict what works for you. We're just figuring out good conventions that don't overburden devs with unnecessary work.

**Comment by nguyenhongphat0** [comment]
> Then please use /api in nginx, and put all graphql endpoints behind /api

Done, Gloria. Please review these new changes and let me know if it looks good to you :pray:

**Comment by vickis** [comment]
awesome work Devs

great security protocols are essential
not over working devs even more so!

hope to have a timeline for you for the installation instance in the
gallery in the next few weeks (Aotearoa/NZ has gone into the highest level
of the new regime (traffic lights) - Red for the whole country as the first
cases of Omricon are beginning o show up - this has caused quite a
disruption across many agencies so some things are taking longer than even
the usual for the last few years

thanks again for your super work team :D

**Comment by gloriajw** [comment]
Phat: I still see the long custom patterns in the nginx config files. Please convert these to /api

**Comment by nguyenhongphat0** [comment]
Can you give me the name of that file, @gloriajw? I changed them to `/api` in `app1_nginx_upstage.conf` and `devapp1_nginx_upstage.conf` already.

**Review by gloriajw — APPROVED** [review]

**Pull request merged**
