### PR TITLE
The script for cleaning up dev instance 

### PR DESCRIPTION
**Pull request by nguyenhongphat0**
To run it: `python3 run_script.py wipe_dev`

### CODE REVIEW

**Review by gloriajw — CHANGES_REQUESTED** [review]
@nguyenhongphat0 this is clever, but an exec() and generic run script is the most dangerous thing in back end code. I cannot let this through, sorry. Please hard-code all imports, and make the script do one thing, for security purposes.

**Comment by nguyenhongphat0** [comment]
Hi @gloriajw, I removed the `exec` with generic script run! Please review the changes and let me know if it's okay to you, thank you very much :pray:

**Review by gloriajw — CHANGES_REQUESTED** [review]
Please remove run_script.py altogether. If you wish to pull terminal colors in, create a terminal_colors.py file, place your scripts subdir in the system folder, since it's not part of Upstage code.

**Comment by nguyenhongphat0** [comment]
Direct calling to the script inside a sub-folder caused `ModuleNotFoundError` when trying to import our SQLAlchemy models and configurations. This is why I made the `run_script.py` at the root and calling these other piece of code:  
image

Is there any other way to do this (run the script inside sub-folder independently, but still be able to import modules)?

**Comment by gloriajw** [comment]
The way we do it in this project is as follows:

appdir = os.path.abspath(os.path.dirname(__file__))
projdir = os.path.abspath(os.path.join(appdir, '..'))
if projdir not in sys.path:
    sys.path.append(appdir)
    sys.path.append(projdir)


This has to exist in every python file (except empty __init__.py files). This allows you to import asset.models, etc, anything you need, by specifying the directory name and them the file name (from stage.assets import AssetConnectionField).

If the script is being called from system/some_dir, .. in the projdir now adds all other directories to your sys,path, and your script will work.

Please make sure this is on top of all of your code, every .py file:

appdir = os.path.abspath(os.path.dirname(__file__))
projdir = os.path.abspath(os.path.join(appdir, '..'))
if projdir not in sys.path:
    sys.path.append(appdir)
    sys.path.append(projdir)

As an aside, this looks redundant, since the above is already an absolute path:

absolutePath = os.path.dirname(appdir)

**Comment by nguyenhongphat0** [comment]
Thank you for the instruction, I got it working now!

Please review the latest changes and let me know if it's look good enough, thank you @gloriajw :pray:

**Comment by nguyenhongphat0** [comment]
Thank you for the instruction, I got it working now!

Please review the latest changes and let me know if it's look good enough, thank you @gloriajw pray

**Pull request merged**
