### PR TITLE
Issue 625 Dark mode indicator

### LINKED ISSUE #625: when chat window minimised, no indicator of new chat
if you minimise the chat window, you do not get any indication of new chat from others.
there should either be some kind of indicator, or else one line of the most recent text still showing when it's minimised. but probably better that there is some kind of indicator.
any ideas?

### PR DESCRIPTION
**Pull request by nguyenhongphat0**
Resolves #625

### CODE REVIEW

**Review by gloriajw — APPROVED** [review]

**Comment by gloriajw** [comment]
Whoops, I approved this, @nguyenhongphat0 , but then realized that I think this should be upstage.live instead of upstage.org.nz:
VUE_APP_JITSI_ENDPOINT=https://streaming1.upstage.org.nz/

**Comment by nguyenhongphat0** [comment]
We don't have any streaming server setup on https://streaming1.upstage.live/, @gloriajw . I don't think we own that domain either :thinking: 
image

**Comment by nguyenhongphat0** [comment]
So that was the correct configuration, since our streaming1 server is on https://streaming1.upstage.org.nz/ :sweat_smile:

**Comment by gloriajw** [comment]
You're right, sorry! We created these for our clinet: streaming1.meta.upstage.live , but we never switched our servers to upstage.live. This is another task that needs to be done. I'll create the domain names, and leave the old ones intact, so we can switch when ready.

**Comment by nguyenhongphat0** [comment]
Sound great! :sunglasses:

**Comment by helenvarley** [comment]
upstage.org.nz is our domain, for the website :)

**Pull request merged**
