### PR TITLE
Issue 877 Integrate Jitsi video bridge low level API

### LINKED ISSUE #877: streaming - any potential in chatmosphere?
one of the projects presented at the FOSSASIA lightning talks was Chatmostphere: 
https://chatmosphere.cc/
https://github.com/Chatmosphere/

it's based on jitsi & has similarities to another chat platform wonder.me, in that your webcam image is round and you can move it around the screen; when you come closer to another person their volume increases, and when you move away from them it decreases. the idea is to make it more like a room where you can move from one group to another, & just hear the conversation that you are closest to.

i don't think the volume increase/decrease feature is so appropriate for us but the possibility to have the webcams moveable and not trapped in the jitsi frame would be cool. i guess embedding chatmosphere instead of jitsi would still contain the webcams within that embed frame, but if you made the frame the size of the stage it could be interesting. also it does not have the same controls popping up that the jitsi window has so maybe possibilities to limit who can open their cam/mic if we want to use in performance ... ????

@gloriajw what do you think, does it look like there could be possibilities for UpStage with this? it's been developed during the pandemic lockdowns by a german couple. if you think there is  potential i could contact them & see if they are interested in maybe collaborating.

### PR DESCRIPTION
**Pull request by nguyenhongphat0**
As discussed before, the Iframe API is simple but it is not allowed for individual player to control his/her own camera around the stage. Integrating low level API gains us more controls of it. Resolves #877 & #934

### CODE REVIEW

**Review by gloriajw — APPROVED** [review]

**Comment by gloriajw** [comment]
This is sooo great. @nguyenhongphat0 : does using the API now mean that we can maintain one jitsi installation and namespace this API out to clients as a standard? Or should we still have separate installations?

**Comment by nguyenhongphat0** [comment]
Jitsi instances doesn't have to be separated. We can have 1 instances for all, or one per each, we just have to put the right configuration in the `VUE_JITSI_ENDPOINT` in `.env` before building 👌

**Comment by gloriajw** [comment]
Fantastic. Let's work together to try and make a punch list of how to set this up and expand for different upstage.live subdomains.

**Comment by vickis** [comment]
superb thanks team :)

**Pull request merged**
