### PR TITLE
Multiframe media scaffolding

### PR DESCRIPTION
**Pull request by nguyenhongphat0**
As discussed the demo penguin would be a multi frame media, so that players can try the animations feature. To scaffold a multi frame media, just put all frame inside a folder of `ui/static/demo` folder. Name of the folder will be used to name the media, like this:
Screen Shot 2022-04-01 at 00 42 42

Continue of #857

### CODE REVIEW

**Comment by vickis** [comment]
Thanks 😊

**Review by gloriajw — APPROVED** [review]
There is a exists_ok=True flag you can pass to makedirs(), to save a step, just fyi.

**Comment by nguyenhongphat0** [comment]
> There is a exists_ok=True flag you can pass to makedirs(), to save a step, just fyi.

Thank you for the tips 🙏

**Comment by vickis** [comment]
thanks 😊

**Pull request merged**
