### PR TITLE
Upstage Studio V1.0

### LINKED ISSUE #25: dropdown menus - multiple selection
As a player, when I need to select options from a dropdown menu, I expect to be able to select multiple options if appropriate, by holding down the shift or ctrl key.

I also expect to see the available options in a logical order, e.g. alphabetical, numerical, time-based etc. (not a random list).

### LINKED ISSUE #603: no way to see file size of uploaded media
i've just realised we have no way to see the file size of an uploaded media item. this is quite important! at the moment, the mobilise/demobilise stage is taking a long time to load - it gets to 144 and then takes ages to load the last media item. i wanted to find out which item it is, & i have a suspicion, but i have no way to know unless i download the item.
previously we could see this information in both the media list and the media preview.

- [ ] it would be great if it showed in the media list AND the media list was sortable - e.g. click on the header of a file size column to see media in the order of largest to smallest filesize, so i could first filter for media on the specific stage, and then sort by file size to quickly find the offending media item
- [ ] it would be great to have on the media item preview, information including the file size, date uploaded, player who uploaded and the file format.

this can come into the post-launch review of the media management that @nguyenhongphat0 has already proposed :smiley:

### PR DESCRIPTION
**Pull request by mister-teddy**
- Server side pagination and sort, with jumper
- Multiple filter by name, media types, owners, stages and date range (resolve #25)
- Show media size, and sort by it (resolve #603)
- Download media and go to container stage (upload and create/edit media will be available in the next version 😅)

Screenshot 2021-10-25 at 00 01 37

### CODE REVIEW

**Comment by nguyenhongphat0** [comment]
Yes you can access the studio from backstage now. And it is on [upstage.live](https://upstage.live/studio/) as well ☝️

**Comment by helenvarley** [comment]
presumably there's going to be an edit button in the manage media column?
(we are going to have to rewrite the media management section of the user manual .,.. )

great to be able to see the file sizes, & i like the green/yellow/red coding so that we can easily see big ones that might cause problems. 

at the moment the sorting is not all working as i expect, but probably you are still working on it. also, when i am scrolled down the page and then click on the messages, i only see a few pixels of that pop-up window. i have to be at the top of the page to access it properly.

**Comment by helenvarley** [comment]
& i approved your requests but they did not go away ...

**Comment by nguyenhongphat0** [comment]
> & i approved your requests but they did not go away ...

Calm down, Helen 😆 The notifications is just mockup of what our "use with permission" will look like, there is no function yet

> at the moment the sorting is not all working as I expect, but probably you are still working on it

Actually the sorting is finished, could you tell me what is wrong with it 🤔 ?

**Comment by helenvarley** [comment]
the filters are working as i expect, & this is GREAT.
what did not work as i expected is the "click to sort ascending / descending" in the columns. i've been trying it a bit more & maybe it is working properly, but the "cancel sorting" is confusing me - if there is only ascending or descending, what does "cancel" do?
sometimes i see the mouse-over for "cancel sorting", other times for ascending or descending, & i'm not sure why ...
if i have sorted for example the date column to be descending, the little green arrow is pointing down, but now i cannot sort it to be ascending, i can only cancel sorting. so i cancel; then the mouse-over only offers me ascending again, so i click to make it ascending - and now the mouse-over is offering me only descending ...

**Comment by nguyenhongphat0** [comment]
Cancel sorting is necessary in multiple sorter criteria. For example: if you're sorting media by `type ascending` + `name descending`, first they will be sorted by media type (avatar > prop > backdrop > audio), then in each group of avatars / props / backdrops,... media with the same type are sorted by name. What if after that you want remove the type grouping so that you can sort by name only? The cancel sorting will do it 💪

**Comment by vickis** [comment]
Cool
Ales sense :)

**Comment by helenvarley** [comment]
ok, but ... i have just now entered the studio, so i haven't filtered or sorted anything. the first item in the list is one that was uploaded 8 months ago. i want to see the most recently uploaded items. when i hover over the date column, the mouse-over says "click to cancel sorting" ... but when i click it, it sorts descending.
none of the other columns had the cancel mouse-over, they all had "click to sort ascending"
so it's still a bit confusing. 
BUT let's not worry about it right now, let's get everything else working & then see if it needs to be tweaked :)

**Pull request merged**
